version: "3"
services:
    xserver:
        image: devrt/xserver
        ports:
            - "3000:80"
        healthcheck:
            test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
            interval: "1s"
            retries: 20
    workspace:
        build: .
        user: vscode
        ports:
            - "3001:3000"
            - "3002:8888"
        volumes:
            - ../:/workspace/src/asd-lab
        environment:
            - DISPLAY=:0
        volumes_from:
            - xserver
        depends_on:
            - xserver
        command: /bin/sh -c "while sleep 1000; do :; done"
