name: ROS

on: [push, pull_request]

jobs:
    ros:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                ros_distribution:
                    - noetic
                include:
                    - docker_image: ubuntu:focal
                      ros_distribution: noetic
                      ros_version: 1
        container:
            image: ${{ matrix.docker_image }}
        steps:
            - name: Setup ROS environment
              uses: ros-tooling/setup-ros@v0.1
              with:
                  required-ros-distributions: ${{ matrix.ros_distribution }}
            - name: Build and test ROS 1
              if: ${{ matrix.ros_version == 1 }}
              uses: ros-tooling/action-ros-ci@v0.2
              with:
                  package-name: car_demo
                  target-ros1-distro: ${{ matrix.ros_distribution }}
            - name: Build and test ROS 2
              if: ${{ matrix.ros_version == 2 }}
              uses: ros-tooling/action-ros-ci@v0.2
              with:
                  package-name: car_demo
                  target-ros2-distro: ${{ matrix.ros_distribution }}
